# Whether this GitHub repo is for a CC-led engineering project
engineering_project: repositories ouvert    
# Whether this repository should be featured on the CC Open Source site's "Projects" page
featured: false
